### ISSUE TITLE
sorting column also wrong on save.

### ISSUE THREAD

**Issue by thegass** [team23/t23_inline_container#7]
Thanks for fixing #2 

But now I found a other sorting issue:

If I save a container-element with t23_inline_container enabled, the sorting is also wrong 

<img width="954" alt="image" src="https://user-images.githubusercontent.com/101392/204792920-93aebf16-3dfb-475d-99cf-21a374d417a6.png">

After i run `./vendor/bin/typo3 container:sorting --apply`

<img width="961" alt="image" src="https://user-images.githubusercontent.com/101392/204793024-6aae20f9-60f6-4bae-a941-ee5f1038e9bc.png">

**Comment by timdreier** [comment]
@thegass thanks for finding out. Mysterious, since everything should be handled by the container Hooks now.


I'll have a look on it as soon as possible!

**Comment by timdreier** [comment]
The problem is that TYPO3 generates the sorting of the content elements automatically. TYPO3 does not consider the sorting value of the container but starts the sorting at 0 since it doesn't respect that the inline table is the same table as the parent table (tt_content).

I haven't found a way to adjust the sorting for the IRRE elements yet. I guess that this should be possible via processDatamapClass. Have to take a deeper look on that.

**Comment by timdreier** [comment]
We managed to fix the sorting on the second save after a new Element is added to a container. However, the fix won't apply if a new element is added.

Would appreciate any help to fix the sorting on creation.

**Comment by timdreier** [comment]
@thegass should be fixed in Version 0.0.11! Great thanks to @bahammes to fix this!

**Comment by thegass** [comment]
@timdreier will have a look at it. thx.
